spring:
  profiles: native
  cloud:
    config:
      server:
        git:
          enabled: false
        native:
          search-locations: "file:///D:/Java/Kata/Java%20Advance/ms-config-properties"
